Models/TodoModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ToDoList.Models
{
    [Table("Todos")]
    public class TodoModel
    {
        [Key]
        public int TodoId { get; set; }
        [Display(Name = "Nazwa")]
        public string Name { get; set; }
        [Display(Name = "Opis")]
        public string Description { get; set; }
        [Display(Name = "Zrobione")]
        public bool Done { get; set; }
        public bool Hide { get; set; }
    }
}

Controllers/TodoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ToDoList.EFTodoRepository;
using ToDoList.Models;

namespace ToDoList.Controllers
{
    public class TodoController : Controller
    {
        private ITodoRepository todoRepository;

        public TodoController(ITodoRepository repository)
        {
            todoRepository = repository;
        }

        public ActionResult Index()
        {
            return View(todoRepository.GetToDoList());
        }

        public ActionResult Details(int id)
        {
            return View(todoRepository.GetTask(id));
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TodoModel todoModel)
        {
            todoRepository.Add(todoModel);

            return RedirectToAction(nameof(Index));
        }

        public ActionResult Edit(int id)
        {
            return View(todoRepository.GetTask(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, TodoModel todoModel)
        {
            todoRepository.Edit(id, todoModel);

            return RedirectToAction(nameof(Index));
        }

        public ActionResult Delete(int id)
        {
            return View(todoRepository.GetTask(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, TodoModel todoModel)
        {
            todoRepository.Delete(id);

            return RedirectToAction(nameof(Index));
        }

        public ActionResult Done(int id)
        {
            var result = todoRepository.GetTask(id);
            
            result.Done = true;

            todoRepository.Edit(id, result);

            return RedirectToAction(nameof(Index));
        }

        public ActionResult Hide(int id)
        {
            var result = todoRepository.GetTask(id);

            if (result.Hide == true)
            {
                result.Hide = false;
            }
            else
            {
                result.Hide = true;
            }

            todoRepository.Edit(id, result);

            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDoList</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Todo" asp-action="Index">ToDoList</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ToDoList
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Todo/Create.cshtml
@model ToDoList.Models.TodoModel

@{
    ViewData["Title"] = "Create";
}

<h4>Nowe zadanie</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Utwórz" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>
<hr />
<div>
    <a asp-action="Index" class="btn btn-secondary">Wróć do listy</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Todo/Delete.cshtml
@model ToDoList.Models.TodoModel

@{
    ViewData["Title"] = "Delete";
}

<div>
    <h5>Czy na pewno chcesz usunąć to zadanie?</h5>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Usuń" class="btn btn-danger" />
    </form>
</div>
<hr />
<div>
    <a asp-action="Index" class="btn btn-secondary">Wróć do listy</a>
</div>

Views/Todo/Details.cshtml
@model ToDoList.Models.TodoModel

@{
    ViewData["Title"] = "Details";
}

<div>
    <h4>Szczegóły zadania</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    <hr />
</div>
<div>
    @Html.ActionLink("Edytuj", "Edit", new { id = Model.TodoId }, new { @class = "btn btn-primary" } )
    <a asp-action="Index" class="btn btn-secondary">Wróć do listy</a>
</div>

Views/Todo/Edit.cshtml
@model ToDoList.Models.TodoModel

@{
    ViewData["Title"] = "Edit";
}

<h4>Edycja zadania</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Zapisz" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>
<hr />
<div>
    <a asp-action="Index" class="btn btn-secondary">Wróć do listy</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Todo/Index.cshtml
@model IEnumerable<ToDoList.Models.TodoModel>

@{
    ViewData["Title"] = "Index";
}

<h4 class="text-center">Lista rzeczy do zrobienia</h4>

<p>
    <a asp-action="Create" class="btn btn-outline-primary">Utwórz zadanie</a>
</p>
<table class="table table-striped">
    <thead>
        <tr>
            <th></th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Done)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            @if (item.Hide == true)
            {
                <td>
                    @Html.ActionLink("", "Hide", new { id = item.TodoId }, new { @class = "bi bi-arrow-down" })
                </td>
            }
            else
            {
                <td>
                    @Html.ActionLink("", "Hide", new { id = item.TodoId }, new { @class = "bi bi-arrow-up" })
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.ActionLink("", "Done", new { id = item.TodoId }, new { @class = "bi bi-check-lg btn btn-outline-success btn-sm" })
                </td>
                <td>
                    @Html.ActionLink("", "Edit", new { id = item.TodoId }, new { @class = "bi bi-pencil-square btn btn-outline-primary" })
                    @Html.ActionLink("", "Details", new { id = item.TodoId }, new { @class = "bi bi-eye-fill btn btn-outline-info" })
                    @Html.ActionLink("", "Delete", new { id = item.TodoId }, new { @class = "bi bi-trash-fill btn btn-outline-danger" })
                </td>
            }
        </tr>
}
    </tbody>
</table>